# Generated by Django 4.2.7 on 2024-05-29 20:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("backtest", "0005_delete_regressionanalysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegressionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "r_squared",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("1.0")),
                        ],
                    ),
                ),
                ("p_value_alpha", models.DecimalField(decimal_places=8, max_digits=10)),
                ("p_value_beta", models.DecimalField(decimal_places=8, max_digits=10)),
                ("risk_free_rate", models.DecimalField(decimal_places=4, max_digits=5)),
                ("alpha", models.DecimalField(decimal_places=8, max_digits=10)),
                ("beta", models.DecimalField(decimal_places=8, max_digits=10)),
                (
                    "market_contribution",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                (
                    "idiosyncratic_contribution",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                (
                    "total_contribution",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                (
                    "market_volatility",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                (
                    "idiosyncratic_volatility",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                (
                    "total_volatility",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                (
                    "portfolio_dollar_beta",
                    models.DecimalField(decimal_places=8, max_digits=15),
                ),
                (
                    "market_hedge_nmv",
                    models.DecimalField(decimal_places=8, max_digits=15),
                ),
                (
                    "backtest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regression_stats",
                        to="backtest.backtest",
                    ),
                ),
            ],
        ),
    ]
