# Generated by Django 4.2.7 on 2024-06-03 12:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regression_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regressionanalysis",
            name="MAE",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="RMSE",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="adjusted_r_squared",
            field=models.DecimalField(
                decimal_places=7,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("1.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="alpha",
            field=models.DecimalField(decimal_places=7, max_digits=15),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="condition_number",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="durbin_watson",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="f_statistic",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="f_statistic_p_value",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="idiosyncratic_contribution",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="idiosyncratic_volatility",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="jarque_bera",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="jarque_bera_p_value",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="p_value_alpha",
            field=models.DecimalField(decimal_places=7, max_digits=15),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="r_squared",
            field=models.DecimalField(
                decimal_places=7,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("1.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="systematic_contribution",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="systematic_volatility",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="total_contribution",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="total_volatility",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
