# Generated by Django 4.2.7 on 2024-05-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regression_analysis", "0002_alter_regressionanalysis_backtest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regressionanalysis",
            name="alpha",
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
    ]
