# Generated by Django 4.2.7 on 2024-05-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("regression_analysis", "0003_alter_regressionanalysis_alpha"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regressionanalysis", name="market_hedge_nmv",
        ),
        migrations.RemoveField(
            model_name="regressionanalysis", name="portfolio_dollar_beta",
        ),
    ]
