# Generated by Django 4.2.7 on 2024-05-30 18:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "regression_analysis",
            "0004_remove_regressionanalysis_market_hedge_nmv_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="regressionanalysis",
            old_name="market_contribution",
            new_name="systematic_contribution",
        ),
        migrations.RenameField(
            model_name="regressionanalysis",
            old_name="market_volatility",
            new_name="systematic_volatility",
        ),
        migrations.AddField(
            model_name="regressionanalysis",
            name="MAE",
            field=models.DecimalField(decimal_places=8, default="0", max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regressionanalysis",
            name="RMSE",
            field=models.DecimalField(decimal_places=8, default="0", max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regressionanalysis",
            name="adjusted_r_squared",
            field=models.DecimalField(
                decimal_places=8,
                default="0",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("1.0")),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regressionanalysis",
            name="condition_number",
            field=models.DecimalField(decimal_places=8, default="0", max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regressionanalysis",
            name="durbin_watson",
            field=models.DecimalField(decimal_places=8, default="0", max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regressionanalysis",
            name="f_statistic",
            field=models.DecimalField(decimal_places=8, default="0", max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regressionanalysis",
            name="f_statistic_p_value",
            field=models.DecimalField(decimal_places=8, default="0", max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regressionanalysis",
            name="jarque_bera",
            field=models.DecimalField(decimal_places=8, default="0", max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regressionanalysis",
            name="jarque_bera_p_value",
            field=models.DecimalField(decimal_places=8, default="0", max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regressionanalysis",
            name="residuals",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name="regressionanalysis",
            name="vif",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="beta",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="p_value_alpha",
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
        migrations.AlterField(
            model_name="regressionanalysis",
            name="p_value_beta",
            field=models.JSONField(default=dict),
        ),
    ]
