# Generated by Django 4.2.7 on 2024-04-11 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("region", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10, unique=True)),
                (
                    "security_type",
                    models.CharField(
                        choices=[
                            ("EQUITY", "EQUITY"),
                            ("FUTURE", "FUTURE"),
                            ("OPTION", "OPTION"),
                            ("INDEX", "INDEX"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"unique_together": {("ticker", "security_type")},},
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strike_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expiration_date", models.DateTimeField()),
                ("option_type", models.CharField(max_length=4)),
                ("contract_size", models.IntegerField()),
                ("underlying_name", models.CharField(max_length=50)),
                ("exchange", models.CharField(blank=True, max_length=25, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "symbol",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option",
                        to="symbols.symbol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Index",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("exchange", models.CharField(max_length=50)),
                (
                    "asset_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="symbols.assetclass",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="symbols.currency",
                    ),
                ),
                (
                    "symbol",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index",
                        to="symbols.symbol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Future",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_code", models.CharField(max_length=10)),
                ("product_name", models.CharField(max_length=50)),
                ("exchange", models.CharField(max_length=25)),
                ("currency", models.CharField(max_length=3)),
                ("contract_size", models.FloatField()),
                ("contract_units", models.CharField(max_length=20)),
                ("tick_size", models.FloatField()),
                ("min_price_fluctuation", models.FloatField()),
                ("continuous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "symbol",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="future",
                        to="symbols.symbol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=150)),
                ("exchange", models.CharField(max_length=25)),
                ("currency", models.CharField(max_length=3)),
                ("industry", models.CharField(default="NULL", max_length=50)),
                ("market_cap", models.IntegerField(blank=True, null=True)),
                ("shares_outstanding", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "symbol",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equity",
                        to="symbols.symbol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cryptocurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cryptocurrency_name", models.CharField(max_length=50)),
                ("circulating_supply", models.IntegerField(blank=True, null=True)),
                ("market_cap", models.IntegerField(blank=True, null=True)),
                ("total_supply", models.IntegerField(blank=True, null=True)),
                ("max_supply", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "symbol",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cryptocurrency",
                        to="symbols.symbol",
                    ),
                ),
            ],
        ),
    ]
