# Generated by Django 4.2.7 on 2024-04-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("symbols", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="future", old_name="contract_untis", new_name="contract_units",
        ),
    ]
