# Generated by Django 4.2.7 on 2024-04-18 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("symbols", "0002_rename_contract_untis_future_contract_units"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cryptocurrency",
            old_name="cryptocurrency_name",
            new_name="name",
        ),
        migrations.RemoveField(model_name="cryptocurrency", name="description",),
    ]
