# Generated by Django 5.0.1 on 2024-01-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="future", name="contract_months",),
        migrations.RemoveField(model_name="future", name="last_trading_day",),
        migrations.RemoveField(model_name="future", name="trading_hours",),
        migrations.AddField(
            model_name="future",
            name="continuous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="future",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
            preserve_default=False,
        ),
    ]
