# Generated by Django 4.2.7 on 2024-06-01 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("symbols", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.BigIntegerField(db_index=True)),
                ("ask", models.DecimalField(decimal_places=4, max_digits=10)),
                ("ask_size", models.DecimalField(decimal_places=4, max_digits=10)),
                ("bid", models.DecimalField(decimal_places=4, max_digits=10)),
                ("bid_size", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotedata",
                        to="symbols.symbol",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "timestamp"],
                        name="market_data_symbol__14c5a8_idx",
                    )
                ],
                "unique_together": {("symbol", "timestamp")},
            },
        ),
        migrations.CreateModel(
            name="BarData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.BigIntegerField(db_index=True)),
                ("open", models.DecimalField(decimal_places=4, max_digits=10)),
                ("close", models.DecimalField(decimal_places=4, max_digits=10)),
                ("high", models.DecimalField(decimal_places=4, max_digits=10)),
                ("low", models.DecimalField(decimal_places=4, max_digits=10)),
                ("volume", models.BigIntegerField()),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bardata",
                        to="symbols.symbol",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "timestamp"],
                        name="market_data_symbol__5a9d7f_idx",
                    )
                ],
                "unique_together": {("symbol", "timestamp")},
            },
        ),
    ]
