# Generated by Django 5.0.1 on 2024-02-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0001_initial"),
        ("symbols", "0002_rename_ticker_cryptocurrency_symbol_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bardata", name="market_data_ticker__a66fa5_idx",
        ),
        migrations.RenameField(
            model_name="bardata", old_name="ticker", new_name="symbol",
        ),
        migrations.AlterUniqueTogether(
            name="bardata", unique_together={("symbol", "timestamp")},
        ),
        migrations.AddIndex(
            model_name="bardata",
            index=models.Index(
                fields=["symbol", "timestamp"], name="market_data_symbol__5a9d7f_idx"
            ),
        ),
    ]
