# Generated by Django 4.2.7 on 2024-04-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0002_quotedata"),
    ]

    operations = [
        migrations.RemoveField(model_name="quotedata", name="volume",),
    ]
