# Generated by Django 4.2.7 on 2024-04-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0003_remove_quotedata_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bardata",
            name="timestamp",
            field=models.BigIntegerField(db_index=True),
        ),
    ]
