# Generated by Django 4.2.7 on 2024-04-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("live_session", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to="live_session.session",
            ),
        ),
    ]
