# Generated by Django 4.2.7 on 2024-04-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("live_session", "0002_alter_account_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketdata",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="market_data",
                to="live_session.session",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="live_session.session",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="live_session.session",
            ),
        ),
        migrations.AlterField(
            model_name="risk",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk",
                to="live_session.session",
            ),
        ),
    ]
