# Generated by Django 4.2.7 on 2024-06-01 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strategy_name", models.CharField(max_length=255)),
                ("tickers", models.JSONField(default=list)),
                ("benchmark", models.JSONField(default=list)),
                ("data_type", models.CharField(max_length=10)),
                ("train_start", models.BigIntegerField(blank=True, null=True)),
                ("train_end", models.BigIntegerField(blank=True, null=True)),
                ("test_start", models.BigIntegerField(blank=True, null=True)),
                ("test_end", models.BigIntegerField(blank=True, null=True)),
                ("capital", models.FloatField(blank=True, null=True)),
                ("strategy_allocation", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.BigIntegerField(blank=True, null=True)),
                (
                    "live_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="live.livesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradeInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=10)),
                ("trade_id", models.PositiveIntegerField()),
                ("leg_id", models.PositiveIntegerField()),
                ("weight", models.FloatField()),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_instructions",
                        to="live.signal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.BigIntegerField(blank=True, null=True)),
                ("ticker", models.CharField(max_length=50)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=10)),
                ("price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("cost", models.DecimalField(decimal_places=4, max_digits=10)),
                ("action", models.CharField(max_length=10)),
                ("fees", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "live_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="live.livesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=4)),
                ("start_timestamp", models.BigIntegerField(blank=True, null=True)),
                (
                    "start_BuyingPower",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "start_ExcessLiquidity",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "start_FullAvailableFunds",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "start_FullInitMarginReq",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "start_FullMaintMarginReq",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "start_FuturesPNL",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "start_NetLiquidation",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "start_TotalCashBalance",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "start_UnrealizedPnL",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                ("end_timestamp", models.BigIntegerField(blank=True, null=True)),
                (
                    "end_BuyingPower",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "end_ExcessLiquidity",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "end_FullAvailableFunds",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "end_FullInitMarginReq",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "end_FullMaintMarginReq",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "end_FuturesPNL",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "end_NetLiquidation",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "end_TotalCashBalance",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "end_UnrealizedPnL",
                    models.DecimalField(decimal_places=4, max_digits=16),
                ),
                (
                    "live_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_data",
                        to="live.livesession",
                    ),
                ),
            ],
        ),
    ]
