# Generated by Django 4.2.7 on 2024-06-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("live", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountsummary",
            old_name="end_BuyingPower",
            new_name="end_buying_power",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="end_ExcessLiquidity",
            new_name="end_excess_liquidity",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="end_FullAvailableFunds",
            new_name="end_full_available_funds",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="end_FullInitMarginReq",
            new_name="end_full_init_margin_req",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="end_FullMaintMarginReq",
            new_name="end_full_maint_margin_req",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="end_FuturesPNL",
            new_name="end_futures_pnl",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="end_NetLiquidation",
            new_name="end_net_liquidation",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="end_TotalCashBalance",
            new_name="end_total_cash_balance",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="end_UnrealizedPnL",
            new_name="end_unrealized_pnl",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="start_BuyingPower",
            new_name="start_buying_power",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="start_ExcessLiquidity",
            new_name="start_excess_liquidity",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="start_FullAvailableFunds",
            new_name="start_full_available_funds",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="start_FullInitMarginReq",
            new_name="start_full_init_margin_req",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="start_FullMaintMarginReq",
            new_name="start_full_maint_margin_req",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="start_FuturesPNL",
            new_name="start_futures_pnl",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="start_NetLiquidation",
            new_name="start_net_liquidation",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="start_TotalCashBalance",
            new_name="start_total_cash_balance",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="start_UnrealizedPnL",
            new_name="start_unrealized_pnl",
        ),
    ]
