# Generated by Django 4.2.7 on 2024-04-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("live", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountsummary",
            old_name="end_timestamp",
            new_name="etimestamp",
        ),
        migrations.RenameField(
            model_name="accountsummary",
            old_name="start_timestamp",
            new_name="stimestamp",
        ),
    ]
