# Generated by Django 4.2.7 on 2024-04-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountsummary",
            name="end_UnrealizedPnL",
            field=models.DecimalField(decimal_places=4, max_digits=16),
        ),
    ]
