# Generated by Django 4.2.7 on 2024-03-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("live", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummaryStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ending_equity", models.FloatField(null=True)),
                ("total_fees", models.FloatField(null=True)),
                ("unrealized_pnl", models.FloatField(null=True)),
                ("realized_pnl", models.FloatField(null=True)),
                (
                    "live_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_stats",
                        to="live.livesession",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="timeseriesstats", name="live_session",),
        migrations.DeleteModel(name="StaticStats",),
        migrations.DeleteModel(name="TimeseriesStats",),
    ]
