# Generated by Django 5.0 on 2024-06-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_rename_end_buyingpower_accountsummary_end_buying_power_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='price',
        ),
        migrations.AddField(
            model_name='trade',
            name='avg_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_value',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
    ]
