# Generated by Django 4.2.7 on 2024-04-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live", "0003_rename_etimestamp_accountsummary_end_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountsummary",
            name="end_timestamp",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accountsummary",
            name="start_timestamp",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
