# Generated by Django 4.2.7 on 2024-05-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live", "0004_alter_accountsummary_end_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signal",
            name="timestamp",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trade",
            name="timestamp",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
