# Generated by Django 4.2.7 on 2024-06-01 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Backtest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strategy_name", models.CharField(max_length=255)),
                ("tickers", models.JSONField(default=list)),
                ("benchmark", models.JSONField(default=list)),
                ("data_type", models.CharField(max_length=10)),
                ("train_start", models.BigIntegerField(blank=True, null=True)),
                ("train_end", models.BigIntegerField(blank=True, null=True)),
                ("test_start", models.BigIntegerField(blank=True, null=True)),
                ("test_end", models.BigIntegerField(blank=True, null=True)),
                ("capital", models.FloatField(blank=True, null=True)),
                ("strategy_allocation", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.BigIntegerField(blank=True, null=True)),
                (
                    "backtest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="backtest.backtest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradeInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=10)),
                ("trade_id", models.PositiveIntegerField()),
                ("leg_id", models.PositiveIntegerField()),
                ("weight", models.FloatField()),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_instructions",
                        to="backtest.signal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_id", models.CharField(max_length=100)),
                ("leg_id", models.CharField(max_length=100)),
                ("timestamp", models.BigIntegerField(blank=True, null=True)),
                ("ticker", models.CharField(max_length=50)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=10)),
                ("price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("cost", models.DecimalField(decimal_places=4, max_digits=10)),
                ("action", models.CharField(max_length=10)),
                ("fees", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "backtest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="backtest.backtest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaticStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("net_profit", models.FloatField(null=True)),
                ("total_fees", models.FloatField(null=True)),
                ("ending_equity", models.FloatField(null=True)),
                ("avg_trade_profit", models.FloatField(null=True)),
                ("total_return", models.FloatField(null=True)),
                ("annual_standard_deviation_percentage", models.FloatField(null=True)),
                ("max_drawdown_percentage", models.FloatField(null=True)),
                ("avg_win_percentage", models.FloatField(null=True)),
                ("avg_loss_percentage", models.FloatField(null=True)),
                ("percent_profitable", models.FloatField(null=True)),
                ("total_trades", models.IntegerField(null=True)),
                ("number_winning_trades", models.IntegerField(null=True)),
                ("number_losing_trades", models.IntegerField(null=True)),
                ("profit_and_loss_ratio", models.FloatField(null=True)),
                ("profit_factor", models.FloatField(null=True)),
                ("sortino_ratio", models.FloatField(null=True)),
                ("sharpe_ratio", models.FloatField(null=True)),
                (
                    "backtest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="static_stats",
                        to="backtest.backtest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeriodTimeseriesStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.BigIntegerField(blank=True, null=True)),
                (
                    "equity_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "period_return",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
                ),
                (
                    "cumulative_return",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
                ),
                (
                    "percent_drawdown",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
                ),
                (
                    "backtest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_timeseries_stats",
                        to="backtest.backtest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyTimeseriesStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.BigIntegerField(blank=True, null=True)),
                (
                    "equity_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "period_return",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
                ),
                (
                    "cumulative_return",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
                ),
                (
                    "percent_drawdown",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
                ),
                (
                    "backtest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_timeseries_stats",
                        to="backtest.backtest",
                    ),
                ),
            ],
        ),
    ]
