# Generated by Django 4.2.7 on 2024-06-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backtest", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trade", old_name="price", new_name="avg_price",
        ),
        migrations.RenameField(
            model_name="trade", old_name="cost", new_name="trade_value",
        ),
    ]
