# Generated by Django 4.2.7 on 2024-02-15 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backtest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("net_profit", models.FloatField(null=True)),
                ("total_return", models.FloatField(null=True)),
                ("max_drawdown", models.FloatField(null=True)),
                ("annual_standard_deviation", models.FloatField(null=True)),
                ("ending_equity", models.FloatField(null=True)),
                ("total_fees", models.FloatField(null=True)),
                ("total_trades", models.IntegerField(null=True)),
                ("num_winning_trades", models.IntegerField(null=True)),
                ("num_lossing_trades", models.IntegerField(null=True)),
                ("avg_win_percent", models.FloatField(null=True)),
                ("avg_loss_percent", models.FloatField(null=True)),
                ("percent_profitable", models.FloatField(null=True)),
                ("profit_and_loss", models.FloatField(null=True)),
                ("profit_factor", models.FloatField(null=True)),
                ("avg_trade_profit", models.FloatField(null=True)),
                ("sharpe_ratio", models.FloatField(null=True)),
                ("sortino_ratio", models.FloatField(null=True)),
                ("alpha", models.FloatField(null=True)),
                ("beta", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TimeseriesStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "equity_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "daily_return",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
                ),
                (
                    "cumulative_return",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
                ),
                (
                    "percent_drawdown",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
                ),
            ],
        ),
        migrations.RemoveField(model_name="pricedata", name="backtest",),
        migrations.RemoveField(model_name="summarystats", name="backtest",),
        migrations.RenameField(
            model_name="backtest", old_name="symbols", new_name="benchmark",
        ),
        migrations.RenameField(
            model_name="trade", old_name="direction", new_name="action",
        ),
        migrations.RenameField(
            model_name="tradeinstruction", old_name="direction", new_name="action",
        ),
        migrations.RenameField(
            model_name="tradeinstruction",
            old_name="allocation_percent",
            new_name="weight",
        ),
        migrations.RemoveField(model_name="backtest", name="end_date",),
        migrations.RemoveField(model_name="backtest", name="start_date",),
        migrations.AddField(
            model_name="backtest",
            name="data_type",
            field=models.CharField(default="BAR", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="backtest",
            name="test_end",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="backtest",
            name="test_start",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="backtest", name="tickers", field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="backtest",
            name="train_end",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="backtest",
            name="train_start",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="fees",
            field=models.DecimalField(decimal_places=4, default="0.0", max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="EquityData",),
        migrations.DeleteModel(name="PriceData",),
        migrations.DeleteModel(name="SummaryStats",),
        migrations.AddField(
            model_name="timeseriesstats",
            name="backtest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeseries_stats",
                to="backtest.backtest",
            ),
        ),
        migrations.AddField(
            model_name="staticstats",
            name="backtest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="static_stats",
                to="backtest.backtest",
            ),
        ),
    ]
