# Generated by Django 4.2.7 on 2024-05-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtest", "0002_alter_signal_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regressionanalysis", name="annualized_return",
        ),
        migrations.RemoveField(
            model_name="regressionanalysis", name="annualized_volatility",
        ),
        migrations.RemoveField(model_name="regressionanalysis", name="sharpe_ratio",),
        migrations.AddField(
            model_name="staticstats",
            name="sharpe_ratio",
            field=models.FloatField(null=True),
        ),
    ]
