# Generated by Django 4.2.7 on 2024-05-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backtest", "0003_remove_regressionanalysis_annualized_return_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staticstats",
            old_name="annual_standard_deviation",
            new_name="annual_standard_deviation_percentage",
        ),
        migrations.RenameField(
            model_name="staticstats",
            old_name="avg_loss_percent",
            new_name="avg_loss_percentage",
        ),
        migrations.RenameField(
            model_name="staticstats",
            old_name="avg_win_percent",
            new_name="avg_win_percentage",
        ),
        migrations.RenameField(
            model_name="staticstats",
            old_name="max_drawdown",
            new_name="max_drawdown_percentage",
        ),
        migrations.RenameField(
            model_name="staticstats",
            old_name="num_lossing_trades",
            new_name="number_losing_trades",
        ),
        migrations.RenameField(
            model_name="staticstats",
            old_name="num_winning_trades",
            new_name="number_winning_trades",
        ),
        migrations.RenameField(
            model_name="staticstats",
            old_name="profit_and_loss",
            new_name="profit_and_loss_ratio",
        ),
    ]
