# Generated by Django 4.2.7 on 2024-05-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "backtest",
            "0004_rename_annual_standard_deviation_staticstats_annual_standard_deviation_percentage_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(name="RegressionAnalysis",),
    ]
