name: midasDatabase CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify your Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests  # Assuming you have tests
      env:
        DJANGO_ENV: development
        SECRET_KEY: ${{ secrets.SECRET_KEY }} 
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }} 
        CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }} 
      run: |
        python manage.py test